### ISSUE TITLE
Linux Single Binary

### ISSUE THREAD

**Issue by chromer030** [liz3/ledit#13]
Merging Xorg and Wayland in a single binary.

**Comment by liz3** [comment]
Is there a GLFW specific api to do that?
Ive found that on my wayland machine unless i ONLY build glfw with wayland support its going to use x11 even though the binary has support for both and thus i though its a better idea to binaries for both platforms.
Although strictly speaking people using this editor are encouraged to build it themselfs.

**Comment by chromer030** [comment]
Agree with that, currently Linux is moving to wayland and Xorg is abandonned, KDE plasma 6 is wayland-default.
Thanks for explanation.
